apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-games-config
  namespace: default
data:
  # Logging Configuration
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"

  # JWT Configuration
  Jwt__Issuer: "fcg-games"

  # API Configuration
  AllowedHosts: "*"

  # Swagger/API Documentation
  ApiTitle: "fcg-games.API"
  ApiVersion: "v1"
