apiVersion: v1
kind: Secret
metadata:
  name: fcg-games-secret
  namespace: default
type: Opaque
stringData:
  # JWT Secret Key
  Jwt__Key: ${JWT_SECRET_KEY}

  # Database Connection String (Full)
  ConnectionStrings__FCGGamesDbConnection: "${DB_CONN_GAMES}"

  # ElasticSearch Connection String
  ElasticSearch__ConnectionString: "${ELASTICSEARCH_CONNECTION_STRING}"
  ApiKey: "${ELASTICSEARCH_API_KEY}"
